name: Auto approve

on:
  repository_dispatch:
     types: [approve-command]
     inputs:
      pull-request:
        description: Pull Request Number
        required: false

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
