on:
  repository_dispatch:
     types: [approve-command]

jobs:
  approve-prs:
    runs-on: ubuntu-latest
    name: Approve valid PRs 
    steps:
      - name: Approve valid workflows
        uses: Cian911/gomerge-action@master
        with:
          repository: ${{ github.repository }}
          github_token: ${{ secrets.GH_TOKEN }}
          labels: "approved"
          approve: "true"
