name: Auto approve

on:
  repository_dispatch:
     types: [approve-command]
     
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - run: echo ${{ github.event.client_payload.slash_command }}
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ github.event.client_payload.slash_command.args.all }}
        
