name: Auto Add Pull request to project

on:
    pull_request:
        types:
            - labeled
            - opened
            - review_requested
            - closed
            - reopened
            - ready_for_review

jobs:
    add-to-project:
        name: Add pull request to project
        runs-on: ubuntu-latest
        steps:
            - uses: actions/add-to-project@main
              with:
                  project-url: https://github.com/orgs/shriproperty/projects/4
                  github-token: ${{ secrets.GH_TOKEN }}
