on:
  repository_dispatch:
    types: [close-command]
jobs:
  closeIssue:
    runs-on: ubuntu-latest
    steps:
        - name: Close Issue
          uses: peter-evans/close-issue@v2
          with:
            issue-number: ${{ github.event.client_payload.slash_command.args.all }}
            comment: |
              Auto-closing this issue.
