name: Auto-Merge
on:
  repository_dispatch:
     types: [merge-command]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    steps:
    - uses: alexwilson/enable-github-automerge-action@main
      with:
        github-token: "${{ secrets.GH_TOKEN }}"
        merge-method: "SQUASH"
